#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home_page:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

shop_page:
  path: /{_locale}/shop
  controller: App\Controller\BoutiqueController::shop
  requirements:
    _locale: '%app.supported_locales%'

wines_page:
  path: /{_locale}/wines
  controller: App\Controller\BoutiqueController::wines
  requirements:
    _locale: '%app.supported_locales%'

product_page:
  path: /{_locale}/wines/{categorie}
  controller: App\Controller\BoutiqueController::product
  requirements:
    _locale: '%app.supported_locales%'

single_page:
  path: /{_locale}/wines/{categorie}/{product}
  controller: App\Controller\BoutiqueController::single_product
  requirements:
    _locale: '%app.supported_locales%'

contact_page:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  requirements:
    _locale: '%app.supported_locales%'

panier_index:
  path: /{_locale}/panier
  controller: App\Controller\PanierController::index
  requirements:
    _locale: '%app.supported_locales%'

panier_ajouter:
  path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
  controller: App\Controller\PanierController::ajouter
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    quantite: ''

panier_enlever:
  path: /{_locale}/panier/enlever/{idProduit}/{quantite}
  controller: App\Controller\PanierController::enlever
  requirements:
    _locale: '%app.supported_locales%'

panier_supprimer:
  path: /{_locale}/panier/supprimer/{idProduit}/
  controller: App\Controller\PanierController::supprimer
  requirements:
    _locale: '%app.supported_locales%'

panier_vider:
  path: /{_locale}/panier/vider/{idProduit}/{quantite}
  controller: App\Controller\PanierController::vider
  requirements:
    _locale: '%app.supported_locales%'

usager_inscription:
  path: /{_locale}/new
  controller: App\Controller\UsagerController:new
  requirements:
    _locale: '%app.supported_locales%'

usager_accueil:
  path: /{_locale}/user
  controller: App\Controller\UsagerController:index
  requirements:
    _locale: '%app.supported_locales%'

panier_validation:
  path: /{_locale}/validation/
  controller: App\Controller\PanierController:valider
  requirements:
    _locale: '%app.supported_locales%'

backoffice_admin:
  path: /{_locale}/backoffice
  controller: App\Controller\AdminController:index
  requirements:
    _locale: '%app.supported_locales%'


